spring.application.name=practica_final

management.endpoints.web.exposure.include=*
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

management.endpoints.web.base-path=/pistaPadel

spring.datasource.url=jdbc:h2:file:./dbdata
spring.datasource.username=sa
spring.h2.console.enabled=true

# Hibernate creará las tablas
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# Esto asegura que data.sql se ejecute DESPUES de crear las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false

spring.jpa.show-sql=true