spring.application.name=practica_final

management.endpoints.web.exposure.include=*
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

management.endpoints.web.base-path=/pistaPadel

spring.datasource.url=jdbc:h2:file:./dbdata
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.jpa.generate-ddl=true
#spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
#spring.jpa.defer-datasource-initialization=true

# BORRAR Y RECREAR LA BD EN CADA ARRANQUE
spring.jpa.hibernate.ddl-auto=create

# ASEGURAR QUE data.sql SE EJECUTA DESPUÉS DE CREAR TABLAS
spring.jpa.defer-datasource-initialization=true

# EJECUTAR data.sql SIEMPRE AL ARRANCAR
spring.sql.init.mode=always

# (OPCIONAL PERO RECOMENDADO) MOSTRAR SQL EN CONSOLA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true